import { auth, provider, db, COLLECTIONS, api, initializeSystem, isAuthorizedAdmin, generateDocumentId, writeAuditLog, OFFICIAL_ADMIN_EMAIL } from './firebase.js';
await initializeSystem();
const loginBtn=document.getElementById('loginBtn');
const adminContent=document.getElementById('adminContent');
const form=document.getElementById('recordForm');
const records=document.getElementById('records');
let currentUser=null;
loginBtn.addEventListener('click',async()=>{try{const result=await api.signInWithPopup(auth,provider);const email=result.user.email.toLowerCase();if(!(await isAuthorizedAdmin(email))){alert('Unauthorized account.');await api.signOut(auth);return;}currentUser=result.user;loginBtn.style.display='none';adminContent.style.display='block';loadRecords();}catch(err){alert(err.message);}});
async function loadRecords(){records.innerHTML='Loading records...';const snap=await api.getDocs(api.collection(db,COLLECTIONS.confirmations));records.innerHTML='';snap.forEach(docSnap=>{const d=docSnap.data();const div=document.createElement('div');div.className='record';div.innerHTML='<div class="record-top"><div><div class="record-id">'+d.documentId+'</div><h3>'+d.volunteerName+'</h3><p>'+d.positionRole+'</p></div><div><strong>'+d.totalHours+' Hours</strong><br>'+d.status+'</div></div>';records.appendChild(div);});}
form.addEventListener('submit',async e=>{e.preventDefault();const id=generateDocumentId();const data={documentId:id,volunteerName:document.getElementById('volunteerName').value,age:document.getElementById('age').value,email:document.getElementById('email').value,phone:document.getElementById('phone').value,positionRole:document.getElementById('positionRole').value,duties:document.getElementById('duties').value,startDate:document.getElementById('startDate').value,endDate:document.getElementById('endDate').value,totalHours:document.getElementById('totalHours').value,issuedOn:new Date().toLocaleDateString(),verifiedBy:'Christopher Shelley',verifiedByEmail:OFFICIAL_ADMIN_EMAIL,status:'Active',createdAt:api.serverTimestamp(),updatedAt:api.serverTimestamp()};await api.setDoc(api.doc(db,COLLECTIONS.confirmations,id),data);await writeAuditLog('record_created',{documentId:id},currentUser.email);form.reset();loadRecords();alert('Verification record created successfully.');});