import { db, COLLECTIONS, api, normalizeDocumentId } from './firebase.js';
const form=document.getElementById('verifyForm');
const input=document.getElementById('documentId');
const modal=document.getElementById('verifyModal');
const closeBtn=document.getElementById('closeVerifyModal');
const card=document.getElementById('resultCard');
const title=document.getElementById('verifyModalTitle');
const modalCard=document.querySelector('#verifyModal .modal-card');
function clean(v){return String(v||'Not listed').replace(/[<>]/g,'')}
function setStatus(type,icon){modalCard.classList.remove('status-valid','status-invalid','status-neutral');modalCard.classList.add('status-'+type);const existing=document.querySelector('.status-corner');if(existing)existing.remove();const badge=document.createElement('div');badge.className='status-corner '+type;badge.textContent=icon;modalCard.appendChild(badge)}
function openModal(){modal.hidden=false;modal.style.display='grid'}
function closeModal(){modal.hidden=true;modal.style.display='none'}
closeModal();
closeBtn.addEventListener('click',closeModal);
modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal()});
function showNotFound(id){setStatus('invalid','✕');title.textContent='Document Not Found';card.className='result-card invalid-card';card.innerHTML='<h3>Document Not Found</h3><p>No verification record exists for <strong>'+clean(id)+'</strong>.</p><p>Please check the Document ID exactly as printed on the form or contact <strong>pray@ask4prayers.com</strong>.</p>';openModal()}
form.addEventListener('submit',async event=>{event.preventDefault();const id=normalizeDocumentId(input.value);setStatus('neutral','…');title.textContent='Checking Records';card.className='result-card';card.innerHTML='<h3>Checking official records...</h3><p>Please wait while the verification system searches for this Document ID.</p>';openModal();try{const snap=await api.getDoc(api.doc(db,COLLECTIONS.confirmations,id));if(!snap.exists()){showNotFound(id);return}const d=snap.data();const active=(d.status||'Active')==='Active';setStatus(active?'valid':'invalid',active?'✓':'✕');title.textContent=active?'Valid Volunteer Confirmation':'Document Marked Invalid';card.className=active?'result-card valid-card':'result-card invalid-card';card.innerHTML='<h3>'+(active?'Valid Volunteer Confirmation':'Document Marked Invalid')+'</h3><p>'+(active?'This document is listed in the official records of The Prayer Project.':'This document exists, but it has been marked invalid or inactive by an administrator.')+'</p><div class="result-grid"><strong>Document ID</strong><span>'+clean(d.documentId)+'</span><strong>Volunteer Name</strong><span>'+clean(d.volunteerName)+'</span><strong>Age</strong><span>'+clean(d.age)+'</span><strong>Position / Role</strong><span>'+clean(d.positionRole)+'</span><strong>Duties</strong><span>'+clean(d.duties)+'</span><strong>Service Dates</strong><span>'+clean(d.startDate)+' through '+clean(d.endDate)+'</span><strong>Total Verified Hours</strong><span>'+clean(d.totalHours)+'</span><strong>Issued On</strong><span>'+clean(d.issuedOn)+'</span><strong>Verified By</strong><span>'+clean(d.verifiedBy)+'</span><strong>Status</strong><span>'+clean(d.status||'Active')+'</span>'+(active?'':'<strong>Invalid Reason</strong><span>'+clean(d.invalidReason||'No reason was provided by the administrator.')+'</span>')+'</div>'}catch(err){console.error(err);setStatus('invalid','!');title.textContent='Verification Error';card.className='result-card invalid-card';card.innerHTML='<h3>Verification Error</h3><p>The verification system could not complete the lookup. This usually means Firestore rules are blocking public reads for volunteerConfirmations.</p>'}});